import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  activitiesSidebar: [
    {type: 'doc', id: 'activities/core/index', label: 'Activities'},
    {
      type: 'category',
      label: 'Core Activities',
      link: {type: 'generated-index'},
      items: [
        'activities/core/boundary-run',
        'activities/core/gathering',
        'activities/core/explore-and-find',
        'activities/core/animal-o',
        'activities/core/clothespin-o',
        'activities/core/draw-the-space',
        'activities/core/geometric-o',
        'activities/core/symbol-o',
        'activities/core/map-walk',
        'activities/core/score-o',
        'activities/core/point-to-point',
      ],
    },
    {
      type: 'category',
      label: 'Camp & Advanced Activities',
      link: {type: 'generated-index'},
      items: [
        'activities/core/map-discussion',
        'activities/core/symbol-relay',
        'activities/core/compass-basics',
        'activities/core/find-your-way-home',
        'activities/core/poison-o',
        'activities/core/line-o',
        'activities/core/star-relay',
        'activities/core/checkpoint-copy-relay',
        'activities/core/window-o',
        'activities/core/vampire-o',
        'activities/core/capture-the-flag-o',
      ],
    },
  ],

  lessonsSidebar: [
    {
      type: 'category',
      label: 'Lesson Plans',
      link: {type: 'doc', id: 'lessons/index'},
      items: [
        {
          type: 'category',
          label: 'Teach at a School',
          link: {type: 'doc', id: 'lessons/school/index'},
          items: [
            {
              type: 'category',
              label: 'Grade K-2',
              link: {type: 'doc', id: 'lessons/school/grade-k-2/index'},
              items: [{type: 'autogenerated', dirName: 'lessons/school/grade-k-2'}],
            },
            {
              type: 'category',
              label: 'Grade 3-5',
              link: {type: 'doc', id: 'lessons/school/grade-3-5/index'},
              items: [{type: 'autogenerated', dirName: 'lessons/school/grade-3-5'}],
            },
            {
              type: 'category',
              label: 'Grade 6+',
              link: {type: 'doc', id: 'lessons/school/grade-6-plus/index'},
              items: [{type: 'autogenerated', dirName: 'lessons/school/grade-6-plus'}],
            },
          ],
        },
        {
          type: 'category',
          label: 'Camp',
          link: {type: 'doc', id: 'lessons/camp/index'},
          items: [
            {
              type: 'category',
              label: 'Camp Intro',
              link: {type: 'doc', id: 'lessons/camp/intro/index'},
              items: [{type: 'autogenerated', dirName: 'lessons/camp/intro'}],
            },
            {
              type: 'category',
              label: 'Camp Skill Development',
              link: {type: 'doc', id: 'lessons/camp/full/index'},
              items: [{type: 'autogenerated', dirName: 'lessons/camp/full'}],
            },
          ],
        },
      ],
    },
  ],

aboutSidebar: [
    {type: 'autogenerated', dirName: 'about'},
  ],

  referenceSidebar: [
    {type: 'autogenerated', dirName: 'reference'},
  ],

  editorsSidebar: [
    {type: 'doc', id: 'editors/index', label: 'For Editors'},
    {type: 'doc', id: 'editors/editing-guide', label: 'Editing Guide'},
    {type: 'doc', id: 'editors/roadmap', label: 'Roadmap'},
    {type: 'doc', id: 'editors/content-table', label: 'Activities Table'},
    {
      type: 'category',
      label: 'Video Scripts',
      link: {type: 'doc', id: 'editors/video-scripts/index'},
      items: [
        {
          type: 'category',
          label: 'Activity Scripts',
          items: [
            {type: 'autogenerated', dirName: 'editors/video-scripts/activities'},
          ],
        },
        {
          type: 'category',
          label: 'Lesson Scripts',
          items: [
            {type: 'autogenerated', dirName: 'editors/video-scripts/lessons'},
          ],
        },
      ],
    },
  ],
};

export default sidebars;
