import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  activitiesSidebar: [
    {
      type: 'category',
      label: 'Core Activities',
      items: [{type: 'autogenerated', dirName: 'activities/core'}],
    },
  ],

  lessonsSidebar: [
    {
      type: 'category',
      label: 'Grade 3-5',
      items: [{type: 'autogenerated', dirName: 'lessons/grade-3-5'}],
    },
  ],

  equipmentSidebar: [
    {type: 'autogenerated', dirName: 'equipment'},
  ],
};

export default sidebars;
