import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  activitiesSidebar: [
    {
      type: 'category',
      label: 'Core Activities',
      items: [{type: 'autogenerated', dirName: 'activities/core'}],
    },
  ],

  lessonsSidebar: [
    {
      type: 'category',
      label: 'Teach at a School',
      link: {type: 'doc', id: 'lessons/school/index'},
      items: [
        {
          type: 'category',
          label: 'Grade K-2',
          link: {type: 'doc', id: 'lessons/school/grade-k-2/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/school/grade-k-2'}],
        },
        {
          type: 'category',
          label: 'Grade 3-5',
          link: {type: 'doc', id: 'lessons/school/grade-3-5/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/school/grade-3-5'}],
        },
        {
          type: 'category',
          label: 'Grade 6+',
          link: {type: 'doc', id: 'lessons/school/grade-6-plus/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/school/grade-6-plus'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Camp',
      link: {type: 'doc', id: 'lessons/camp/index'},
      items: [
        {
          type: 'category',
          label: 'Camp Intro',
          link: {type: 'doc', id: 'lessons/camp/intro/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/camp/intro'}],
        },
        {
          type: 'category',
          label: 'Camp Skill Development',
          link: {type: 'doc', id: 'lessons/camp/full/index'},
          items: [{type: 'autogenerated', dirName: 'lessons/camp/full'}],
        },
      ],
    },
  ],

  equipmentSidebar: [
    {type: 'autogenerated', dirName: 'equipment'},
  ],

  referenceSidebar: [
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
