export interface ActivitySummary {
  name: string;
  tagline: string;
  time: string;
  lessons: string;
  status: 'done' | 'tbd';
  image: string;
  link: string;
  description: string;
  steps: string[];
}

const activities: ActivitySummary[] = [
  {
    name: 'Boundary Run',
    tagline: 'Travel the boundary of the play area',
    time: 'Walk the boundary + 5 min discussion',
    lessons: '3-5 L1, K-2 L1, 6+ L1',
    status: 'done',
    image: '/curriculum/img/activities/boundary-run.png',
    link: '/curriculum/activities/core/boundary-run',
    description: 'The leader runs around the boundary of the play area while participants follow. Then participants show what they learned by identifying which spots are inside or outside the boundary.',
    steps: [
      'Gather at a starting point',
      'Explain the boundary run',
      'Run together, stay behind the leader',
      'Run the boundary',
      'Quiz inside vs. outside',
      'Discuss off-limits areas',
    ],
  },
  {
    name: 'Gathering',
    tagline: 'Return to the teacher on a signal',
    time: '30-45 minutes',
    lessons: '3-5 L1, K-2 L1',
    status: 'done',
    image: '/curriculum/img/activities/gathering.png',
    link: '/curriculum/activities/core/gathering',
    description: 'Students spread out within the boundary, then return to the leader when they hear the gathering signal. Builds the habit of listening for and responding to a recall signal while moving.',
    steps: [
      'Establish a gathering signal',
      'Spread out within the boundary',
      'Signal to gather',
      'Repeat with increasing distance',
    ],
  },
  {
    name: 'Explore & Find',
    tagline: 'In pairs, explore to find animal checkpoints',
    time: '5-10 minutes',
    lessons: '3-5 L2, K-2 L2',
    status: 'tbd',
    image: '',
    link: '',
    description: 'A less structured version of Animal-O. Students explore freely within the boundary to find animal checkpoints and report back what they found. No clue sheet, no required order.',
    steps: [
      'Pair up',
      'Explore within the boundary to find animal checkpoints',
      'Return on the gathering signal',
      'Report what you found and where',
    ],
  },
  {
    name: 'Animal-O',
    tagline: 'Use a clue sheet to find checkpoints in order',
    time: '15-30 minutes',
    lessons: '3-5 L3, K-2 L2/L4, 6+ L1',
    status: 'done',
    image: '/curriculum/img/activities/animal-o.png',
    link: '/curriculum/activities/core/animal-o',
    description: 'Explore within the boundary to find animal checkpoints. Use a clue sheet to find checkpoints in order. Repeat for a faster time. Repeat from memory.',
    steps: [
      'Pick up a clue sheet at the start',
      'Find and confirm each animal in order',
      'Return to the finish after the last checkpoint',
    ],
  },
  {
    name: 'Clothespin-O',
    tagline: 'Find hidden objects and describe their locations',
    time: '30-45 minutes',
    lessons: 'K-2 L3',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/clothespin-o',
    description: 'Students search for hidden clothespins within the boundary. When they find one, they bring it back and describe where they found it. Builds observation, spatial communication, and teamwork.',
    steps: [
      'Explore the boundary',
      'Search for hidden clothespins',
      'Bring each one back and describe where you found it',
      'Help a friend find one',
    ],
  },
  {
    name: 'Geometric-O',
    tagline: 'Use a simple map to do progressively harder courses',
    time: '30-60 minutes',
    lessons: '3-5 L4, K-2 L6, 6+ L1',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/geometric-o',
    description: 'Students orient a simple pattern map using colored landmarks, then visit checkpoints in order. The bridge between clue sheets and orienteering maps.',
    steps: [
      'Whiteboard introduction: orient the map',
      'Pair up and receive maps',
      'Visit checkpoints in order, starting with triangle',
      'Progress to harder courses',
    ],
  },
  {
    name: 'Symbol-O',
    tagline: 'Understand map symbols and the features they represent',
    time: '30-60 minutes',
    lessons: '3-5 L5, 6+ L2',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/symbol-o',
    description: 'Learn map symbols and the features they represent in the terrain. Use a clue sheet to visit different features within a boundary.',
    steps: [
      'Run the boundary',
      'Explore to find checkpoints',
      'Learn map symbols from the key',
      'Visit checkpoints matching symbols in order',
    ],
  },
  {
    name: 'Map Walk',
    tagline: 'Walk a route together, matching map symbols to real features',
    time: '15-20 minutes',
    lessons: '3-5 L5, 6+ L2',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/map-walk',
    description: 'The leader walks a route while students follow along on their own maps, matching symbols on the map to features in the real world.',
    steps: [
      'Distribute maps and orient them',
      'Walk the route together',
      'Stop at features and match to map symbols',
      'Students take turns leading',
    ],
  },
  {
    name: 'Score-O',
    tagline: 'Visit as many checkpoints as possible in any order',
    time: '15-30 minutes',
    lessons: '3-5 L6, 6+ L3',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/score-o',
    description: 'Students use an orienteering map to find as many checkpoints as possible within a time limit, visiting them in any order they choose.',
    steps: [
      'Orient the map at the start',
      'Choose which checkpoint to visit first',
      'Navigate to checkpoints in any order',
      'Return before time runs out',
    ],
  },
  {
    name: 'Point-to-Point',
    tagline: 'Complete a course using an orienteering map',
    time: '30-60 minutes',
    lessons: '3-5 L6, 6+ L5',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/point-to-point',
    description: 'Students navigate a course visiting checkpoints in numbered order using an orienteering map. This is real orienteering: detailed map reading, route choice, and confirming each checkpoint before moving on.',
    steps: [
      'Orient the map together',
      'Plan a route to the first checkpoint',
      'Visit checkpoints in order, punching at each one',
      'Return to the finish',
    ],
  },
  {
    name: 'Reverse Score-O',
    tagline: 'Find controls and mark their locations on the map',
    time: '15-30 minutes',
    lessons: '6+ L4',
    status: 'tbd',
    image: '',
    link: '',
    description: 'Students receive a blank map with only landmarks, find controls in the terrain, and mark where they are on the map. Reverses the usual direction and deepens the map-terrain connection.',
    steps: [
      'Receive a blank map with landmarks only',
      'Find controls in the terrain',
      'Mark each control location on the map',
      'Compare your map to the master',
    ],
  },
  {
    name: 'Poison-O',
    tagline: 'Score-O where wrong checkpoints lose points',
    time: '15-30 minutes',
    lessons: '3-5 L6 (ext), 6+ L3',
    status: 'done',
    image: '',
    link: '/curriculum/activities/core/score-o',
    description: 'Set up a Score-O course, but add extra "poison" checkpoints not on the student\'s map. Recording a poison checkpoint loses points. Rewards careful map reading.',
    steps: [
      'Same as Score-O, with extra poison checkpoints added',
      'Correct checkpoints earn points, poison checkpoints cost points',
      'Students must match what they see to what is on their map',
    ],
  },
  {
    name: 'Basketball-O',
    tagline: 'Orienteering on a basketball court map',
    time: '30-60 minutes',
    lessons: '3-5 LA (Indoor)',
    status: 'tbd',
    image: '',
    link: '',
    description: 'Orienteering courses using the lines and features of a basketball court. Students orient a court map and visit checkpoints in order.',
    steps: [
      'Look at the court map together',
      'Orient the map to match the real court',
      'Visit checkpoints in numbered order',
      'Progress to harder courses',
    ],
  },
  {
    name: 'Relay Race',
    tagline: 'Teams compete in relay format',
    time: '20-30 minutes',
    lessons: '6+ L6',
    status: 'tbd',
    image: '',
    link: '',
    description: 'Teams take turns completing orienteering courses in relay format. One runner goes at a time; when they finish, the next teammate starts.',
    steps: [
      'Form teams of 3-4',
      'First runner takes a map and completes the course',
      'Tag the next teammate',
      'First team to finish all runners wins',
    ],
  },
];

export default activities;
